### ISSUE TITLE
Bookings > Booking Card Image has dark Grey when image isnotloaded... change it to Grey.Shade200 [ Clcik to see more ]

### ISSUE THREAD

**Issue by XeroDays** [apptexsolutions/Omnii#64]

**Comment by Sikander-shah007** [comment]
Booking card

**Comment by XeroDays** [comment]
Is it fixed? IT has a  dark grey color when image not fully loaded.

**Comment by XeroDays** [comment]
I am talking about this


![Image](https://user-images.githubusercontent.com/38852291/210200086-3843a551-9745-40f4-8416-9bb75e6a9879.png)
